name: CD - AWS App Runner
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-token: ${{ secrets.AWS_ACCESS_KEY }}
      - name: Login to Amazon ECR
        run: # Push para o ECR e Update no App Runner